---
# Audit Worker ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-worker-config
  namespace: securerepo
data:
  KAFKA_BROKER: "kafka:9092"
  QDRANT_URL: "http://qdrant:6333"
  EMBEDDING_URL: "http://embedding:8080/embed"
  # FOUNDATION_MODELS_URL: "https://foundation-models.api.cloud.ru/v1"
  FOUNDATION_MODELS_URL: "https://4826d203-afc2-473b-a666-83a5ae3b2834.modelrun.inference.cloud.ru/v1"
  LLM_MODEL: "qwen2.5-coder-7b-instruct-abliterated:latest"
  HTTP_TIMEOUT: "240"
  EMBEDDING_TIMEOUT: "240"
---
# Audit Worker Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-worker
  namespace: securerepo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-worker
  template:
    metadata:
      labels:
        app: audit-worker
    spec:
      containers:
      - name: audit-worker
        image: xravil/securerepo-audit-worker:v0.0.1
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: audit-worker-config
        env:
        - name: FOUNDATION_MODELS_API_KEY
          valueFrom:
            secretKeyRef:
              name: fm-secret
              key: FM_TOKEN
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_URL
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 2
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
