# PostgreSQL Secret
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: securerepo
type: Opaque
data:
  POSTGRES_PASSWORD:   # Set your HuggingFace token here (base64 encoded)
  POSTGRES_URL: 
  