apiVersion: v1
kind: Secret
metadata:
  name: langfuse-secrets
  namespace: securerepo
type: Opaque
data:
  NEXTAUTH_SECRET:  # Set your HuggingFace token here (base64 encoded)
  SALT:  # Set your HuggingFace token here (base64 encoded)
  ENCRYPT_KEY:  # Set your HuggingFace token here (base64 encoded)
  DATABASE_URL:  # Set your HuggingFace token here (base64 encoded)
  LANGFUSE_INIT_USER_EMAIL:  # Set your HuggingFace token here (base64 encoded)
  LANGFUSE_INIT_USER_PASSWORD:  # Set your HuggingFace token here (base64 encoded)
  LANGFUSE_INIT_USER_NAME:  # Set your HuggingFace token here (base64 encoded)
  SECUREREPO_PUBLIC_KEY:  # Set your HuggingFace token here (base64 encoded)
  SECUREREPO_SECRET_KEY:  # Set your HuggingFace token here (base64 encoded)