# FM Secret
apiVersion: v1
kind: Secret
metadata:
  name: OAPI-Secret
  namespace: securerepo
type: Opaque
data:
  OAPI_TOKEN:    # Set your HuggingFace token here (base64 encoded)
  OAPI_MODELS_URL: 